### ISSUE TITLE
Create basic ui components

### ISSUE THREAD

**Issue by ericafenyo** [ericafenyo/auth-dashboard#15]
I will be creating all the UI components from scratch to reduce heavy library imports (won't list names). 

###  Form
- [ ]  [InputText](https://github.com/ericafenyo/auth-dashboard/issues/1)
- [ ]  [InputPassword](https://github.com/ericafenyo/auth-dashboard/issues/2)
- [ ] [Textarea](https://github.com/ericafenyo/auth-dashboard/issues/3)
- [ ] [PhotoPicker](https://github.com/ericafenyo/auth-dashboard/issues/4)
- [ ] [Checkbox](https://github.com/ericafenyo/auth-dashboard/issues/5)
- [ ] [Radio](https://github.com/ericafenyo/auth-dashboard/issues/6)
- [ ] [Button](https://github.com/ericafenyo/auth-dashboard/issues/7)

### Navigation
- [ ] [Header](https://github.com/ericafenyo/auth-dashboard/issues/8)
- [ ] [Avatar](https://github.com/ericafenyo/auth-dashboard/issues/9)

### Notification
- [ ] [Alert](https://github.com/ericafenyo/auth-dashboard/issues/10)
- [ ] [Notice](https://github.com/ericafenyo/auth-dashboard/issues/11)
- [ ] [LoadingIndicator](https://github.com/ericafenyo/auth-dashboard/issues/12)

### Popups
- [ ] [Overlay](https://github.com/ericafenyo/auth-dashboard/issues/13)
- [ ] [Modal](https://github.com/ericafenyo/auth-dashboard/issues/14)
